### ISSUE TITLE
Sanctum v3.3 - unable to logout

### ISSUE THREAD

**Issue by yanpenalva** [laravel/sanctum#513] opened 2024-04-25 02:44 UTC
### Sanctum Version

3.3

### Laravel Version

10.4

### PHP Version

8.3

### Database Driver & Version

Any

### Description

Hello!!
I've noticed a problem that when I log out using the application's web guard, it doesn't seem to completely delete the session. It seems that this has been fixed in sanctum in version 4, but is there anything that can be done in version 3.3 for laravel 10? is there any conflict in upgrading to version 4 while still in laravel 10? 

The solution seems to have been something mentioned in the issue [511](https://github.com/laravel/sanctum/pull/511)

Thank you in advance for the space to air your doubts and problems.

### Steps To Reproduce

The same of this issue:

https://github.com/laravel/sanctum/pull/511

**Comment by crynobone** [comment] 2024-04-25 03:05
Duplicate of #512

**Closed as completed by crynobone** 2024-04-25 03:05 UTC
